export const TODO_REQUEST = 'TODO_REQUEST';
export const TODO_SUCCESS = 'TODO_SUCCESS';
export const TODO_FAILED = 'TODO_FAILED';

export const SEARCH_BY_ALPHABET = 'SEARCH_BY_ALPHABET';
export const SEARCH_BY_TODONAME = 'SEARCH_BY_TODONAME';
export const SEARCH_BY_COMPLETED = 'SEARCH_BY_COMPLETED';